# Generated by Django 4.0.1 on 2022-11-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclient',
            name='first_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='telegramclient',
            name='last_name',
            field=models.CharField(blank=True, max_length=1000, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramclient',
            name='type',
            field=models.CharField(blank=True, max_length=1000, verbose_name='type'),
        ),
    ]
